### ISSUE TITLE
Username appears in black on a dark theme

### ISSUE THREAD

**Issue by VirtueAvatar** [HudsonGTV/BetterDiscordPlugins#1]
I use AMOLED-Cord theme, a "darker than dark theme" for betterdiscord, and I can't see the username unless I select the text to invert the colours. If I disable AMOLED-Cord, I can barely read it - but the text is still black.

Your screenshot preview shows the text is white, which would work in both of the above scenarios. 

What could be causing this to go black?

**Comment by VirtueAvatar** [comment]
![discordusername-2024-05-18 14_24_33-Window](https://github.com/HudsonGTV/BetterDiscordPlugins/assets/7401849/9b70fb57-f57b-4406-9b23-b433e69bf56d)

each line looks like this

and standard dark theme looks like this:

![discordusername-2024-05-18 14_26_02-Window](https://github.com/HudsonGTV/BetterDiscordPlugins/assets/7401849/b5fc429f-d712-4bb1-b2da-6fae59ca2448)

**Comment by Jcat4609** [comment]
Sorry for the necro, but I've found a small workaround to make the colour white (or any other colour if you know the hex for it).

If you edit the plugin in BetterDiscord and head to line 179, you should find a line called ".hg-username-handle {";
Adding a line directly under font-size called "color: #FFFFFF;" will make the colour white until this is properly fixed/implemented by the author.
![image](https://github.com/user-attachments/assets/cadc0e1c-c87f-45dd-8a55-f7212d05e309)
Make sure that the color field is above the closed curly bracket!

Here is an example with the AMOLED theme enabled.
![image](https://github.com/user-attachments/assets/41d0633c-eb66-4e36-8fb8-6d39342b1ec4)

Hope this helps you out a bit.

**Comment by HudsonGTV** [comment]
My apologies for not addressing this sooner. I will probably add an option to customize the color to work with differing themes. For now, use the fix given by jcat.

**Comment by VirtueAvatar** [comment]
Thanks jcat, the workaround works.

Not sure whether to close this issue since it still exists within the plugin, so will leave it open for the moment.

**Comment by HudsonGTV** [comment]
Hi, I finished fixing it. You can download the plugin directly from the repo or wait a few days for BD to see the new update and prompt you for it. I also added the ability to change the username colors to work better with whatever theme you are using and fixed some username handle prefixes not appearing due to discord updates.

Please feel free to open a new issue if you experience any additional problems.
