### ISSUE TITLE
'Always Show Friends List Username' option not working

### ISSUE THREAD

**Issue by cln1github** [HudsonGTV/BetterDiscordPlugins#2]
When option is turned on, Discord continues to show default behavior (only showing username on hover).

**Comment by HudsonGTV** [comment]
Hello,

Sorry for the late fix. I have resolved this issue in the latest update. Discord changed the names of CSS attributes breaking the feature, but I have changed them over to the new ones. If you experience any additional problems, please feel free to open an new issue.
