### ISSUE TITLE
'Disable for Reactions' option?

### ISSUE THREAD

**Issue by cln1github** [HudsonGTV/BetterDiscordPlugins#3]
I use a relatively high and narrow window resolution for Discord, meaning that this mod basically makes reactions unreadable. In its current state the username and handle take up over half the text window width. It would be nice to be able to turn off the mod functionality only for reactions.
![Screenshot 2024-05-19 005742](https://github.com/HudsonGTV/BetterDiscordPlugins/assets/170210469/30c607e6-8c42-4aaa-8dfc-6eadedefed72)
In this image it's not too bad since my username and the message are short, but it gets out of control very quickly.

**Comment by lirpa001** [comment]
Agreed, reactions plus Usernames are a bit bloated in the narrow window.

**Comment by HudsonGTV** [comment]
Hi,

Assuming you meant the reply message, I can definitely add an option to disable displaying usernames there. Sorry for the late response. I will close this issue once I release it.

**Comment by HudsonGTV** [comment]
I have added an option to turn off the username in replies. You may directly download the new version from this repo, or you may wait a few days for it to be pushed to the BetterDiscord plugins repo
